name: Pytests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up python interpreter
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: run tests
      run: |
        python3 -m pytest